### ISSUE TITLE
None or invalid value for

### ISSUE THREAD

**Issue by karco** [claudegel/sinope-gt125#18] opened 2020-06-03 16:11 UTC
Hello, first of all, thank you for your integration work for Sinope products. I moved from Neviweb integration to GT125 last week. Since then, I have noticed a lot of errors from the integration. Here are some examples;

2020-06-03 11:10:14 WARNING (SyncWorker_0) [custom_components.sinope] Error code: 7ffc (None or invalid value for 79760000)
2020-06-03 11:11:57 WARNING (SyncWorker_7) [custom_components.sinope] Error code: 7ffc (None or invalid value for 69710000)
2020-06-03 11:12:03 WARNING (SyncWorker_19) [custom_components.sinope] Error code: 7ffc (None or invalid value for 33080000)
2020-06-03 11:12:09 WARNING (SyncWorker_8) [custom_components.sinope] Error code: 7ffc (None or invalid value for 147c0000)
2020-06-03 11:12:12 WARNING (SyncWorker_5) [custom_components.sinope] Error code: 7ffc (None or invalid value for fc070000)
2020-06-03 11:12:15 WARNING (SyncWorker_11) [custom_components.sinope] Error code: 7ffc (None or invalid value for 79760000)
2020-06-03 11:13:58 WARNING (SyncWorker_11) [custom_components.sinope] Error code: 7ffc (None or invalid value for 69710000)
2020-06-03 11:14:04 WARNING (SyncWorker_17) [custom_components.sinope] Error code: 7ffc (None or invalid value for 33080000)
2020-06-03 11:14:10 WARNING (SyncWorker_9) [custom_components.sinope] Error code: 7ffc (None or invalid value for 147c0000)
2020-06-03 11:14:13 WARNING (SyncWorker_15) [custom_components.sinope] Error code: 7ffc (None or invalid value for fc070000)
2020-06-03 11:14:16 WARNING (SyncWorker_16) [custom_components.sinope] Error code: 7ffc (None or invalid value for 79760000)
2020-06-03 11:15:59 WARNING (SyncWorker_1) [custom_components.sinope] Error code: 7ffc (None or invalid value for 69710000)
2020-06-03 11:16:05 WARNING (SyncWorker_17) [custom_components.sinope] Error code: 7ffc (None or invalid value for 33080000)
2020-06-03 11:16:11 WARNING (SyncWorker_12) [custom_components.sinope] Error code: 7ffc (None or invalid value for 147c0000)
2020-06-03 11:16:14 WARNING (SyncWorker_13) [custom_components.sinope] Error code: 7ffc (None or invalid value for fc070000)
2020-06-03 11:16:17 WARNING (SyncWorker_18) [custom_components.sinope] Error code: 7ffc (None or invalid value for 79760000)

Do you have a solution or advice to solve the problem?

**Comment by claudegel** [comment] 2020-07-15 02:54
Hi, sorry I was away and didn't see your post. I'll look into this tomorrow

**Comment by claudegel** [comment] 2020-07-16 00:06
The code 7ffc stand for «No value / Invalid / Disabled» received in the thermostat response for your query.
I'll update `__init__.py` so we can get the full binary response so we can see what it is all about.
I know that Sinopé is working a lot in there code so it could be that they are updating the devices or the GT125 and during that  time, responses are blocked.

**Comment by claudegel** [comment] 2020-07-16 01:52
I've created a new branch Data-log.
please copy __init__.py in your custom_components/sinope and restart HA
We wil get more info about that error. Send me your log for the error

**Comment by claudegel** [comment] 2020-07-18 21:09
Did you load the new branch ?

**Comment by claudegel** [comment] 2020-08-02 14:16
I'm closing this issue as unable to reproduce and no followup from @karco. Feel free to reopen if you have more info

**Closed by claudegel** 2020-08-02 14:16 UTC
